name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: SFTP Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.0
      with:
        # username
        username: ${{ secrets.remoteUser }}
        server: ${{ secrets.repoteHost }}
        ssh_private_key: ${{ secrets.sshPrivateKey }}
        remote_path: ${{ secrets.target }}
        args: -o ConnectTimeout=5
