name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: ssh deploy
      uses: easingthemes/ssh-deploy@v2.1.2
      with:
        SSH_PRIVATE_KEY: ${{  secrets.sshPrivateKey  }}
        REMOTE_HOST: ${{  secrets.remoteHost  }}
        REMOTE_USER: ${{  secrets.remoteUser  }}
        TARGET: ${{  secrets.target  }}
